baseURL = 'https://oscarzt20.github.io/'
languageCode = 'es-mx'
title = 'oscarzt20'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowBreadCrumbs = true
  showtoc = true
  tocopen = true
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  hideSummary = false
  mainSections = ["proyectos", "recursos", "apuntes", "pasatiempos", "recetas"]

  [params.homeInfoParams]
    Title = "oscarzt20 | Blog & Notas"
    Content = "Soy Oscar, desarrollador. En este blog comparto lo que hago, lo que aprendo y lo que me inspira, desde proyectos personales hasta apuntes técnicos o pasatiempos que me ayudan a seguir creando."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/oscarzt20"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/oscarzt20"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/oscarzt20/"

[menu]
  [[menu.main]]
    name = "Portafolio"
    url = "/proyectos/"
    weight = 1

  [[menu.main]]
    name = "Recursos / Guías"
    url = "/recursos/"
    weight = 2

  [[menu.main]]
    name = "Estudios"
    url = "/apuntes/"
    weight = 3

  [[menu.main]]
    name = "Entretenimiento"
    url = "/pasatiempos/"
    weight = 4

  [[menu.main]]
    name = "Recetas"
    url = "/recetas/"
    weight = 5
